spring:
  application:
    name: hr-apigateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**
          filters:
            - StripPrefix=1
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**
          filters:
            - StripPrefix=1
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
